name: rick_and_morty_wiki
description: "Rick And Morty Wiki"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.4.1
  dio: ^5.9.0
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  mobx_codegen: ^2.7.2
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
